export { pidogApi, PiDogApiError } from './api/client'
export {
  buildApiRequestUrl,
  buildApiUrl,
  buildCameraStreamUrl,
  connectionErrorMessage,
  defaultSettings,
  loadSettings,
  normalizeHost,
  saveSettings,
  usesLocalPiDogProxy,
} from './api/settings'
export type {
  AssistantControlAction,
  AssistantControlResponse,
  AssistantStatus,
  AssistantStatusResponse,
  ChatResponse,
  ChatSource,
  ClearAssistantHistoryResponse,
  CommandResponse,
  ConnectionSettings,
  HeadResponse,
  HealthResponse,
  SensorsResponse,
  VisionBox,
  VisionEnrollResponse,
  VisionFace,
  VisionInferenceResponse,
  VisionGuardResponse,
  VisionGuardTarget,
  VisionGuardTargetsResponse,
  VisionObject,
  VisionObjectEnrollResponse,
} from './api/types'
